src/app/+run-tale/run-tale/modals/select-data-dialog/select-data-dialog.component.ts, src/app/+run-tale/run-tale/tale-files/tale-files.component.ts
What kind of change does this PR introduce?
[x] Bugfix
Updating `dataSet` fails due to the missing keyword.
`_modelType` is included in `dataSet` during `PUT /tale/:id`
No
=> Include _modelType in dataSet handling

src/app/+run-tale/run-tale/run-tale.component.html, src/app/+run-tale/run-tale/run-tale.component.ts
Multiple upcoming features will require modifying the dropdown menu to include new or expanded items. 
Preemptively stub-out upcoming methods to (hopefully) prevent a merge conflict.
* Added icons to the Run view dropdown menu
* Reordered dropdown items to match mockups (slight divergence aside)
* No "Duplicate Tale" in mockups
* Only one "Export" option going forward
* Grouped Duplicate/Publish/Export together for now
* Added new Run view dropdown menu items (currently noops/stubs):
* Save Tale Version
* Recorded Run
* Connect to Git repository
4. Navigate to the Run view for the Tale
5. Expand the dropdown at the …
=> Expand Run view paddleboard dropdown, add icons

src/app/+user-settings/configure-accounts/configure-accounts.component.ts
Fixes #58 
Use origin instead of a hard-coded URL
Prerequisites: Disconnect DataONE account
3. Navigate to the Settings view
4. Disconnect DataONE account, if you haven't already
5. Click "Connect Account" beside DataONE in the list
6. Sign in with OAuth, if necessary
* You should be redirected to the Settings view (your original starting location)
=> Fix Settings view redirect URL to use origin 

src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.html
Users on the Run > Metadata view can still click "Edit" for Tales which they do not have proper access, even though the Save operation will certainly return a 403.
Fixes #22 
Hide the button for users with improper access to the Tale.
Prerequisites: at least one Tale you do not own (e.g. LIGO)
3. Navigate to the Run > Metadata view for a Tale that you do not own
* You should not see the "Edit" button at the bottom of the view
4. Navigate to the Run > Metadata view for a Tale that you *do* own
* You should see the "Edit" button at the bottom of the view
=> Hide edit Tale button without proper access

src/app/files/file-explorer/modals/rename-dialog/rename-dialog.component.html, src/app/files/file-explorer/modals/rename-dialog/rename-dialog.component.ts
The rename dialog has the word "folder" hard-coded in it. This is obviously confusing when it appears to rename a file.
Fixes #38 
Reword dialog to say "item" instead of "folder", which should cover both cases.
Prerequisites: at least one Tale created, at least one file uploaded
* You should be brought to the Run view
4. Navigate to Run > Files > Home
5. Upload a file, if you haven't already
6. Expand the dropdown beside the file and choose "Rename"
* The `rename-dialog` should appear
* The prompt should now say `Item Name` instead of `Folder Name`
=> Reword Rename dialog to cover both files and folders

src/app/+tale-catalog/tale-catalog.module.ts, src/app/+tale-catalog/tale-catalog/components/my-tales/my-tales.component.html, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.html, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts, src/app/+tale-catalog/tale-catalog/pipes/search-tales.pipe.ts, src/app/+tale-catalog/tale-catalog/tale-catalog.component.html, src/app/+tale-catalog/tale-catalog/tale-catalog.component.ts
Search box on the `tale-catalog` view is currently just a placeholder.
Fixes #35 
Implement the search function in the "Public Tales" and "My Tales" views
My assumption (because the search box is above the "Running Tales" section of the UI) was that the search filter should affect Running Tales as well. If this was incorrect, I can adjust it so that the search only affects the lower section (but would likely also opt to move the search box in this case).
Prerequisites: several Tales created, LIGO Tale added (public), one or more Tales running
3. Click `Tale Catalog` in the navbar
* You should be brought to the "Public Tales" view
4. Enter "LIGO" into the search box
* All but the LIGO Tale should be …
=> Added working search box to tale-catalog

src/app/api/api.module.ts, src/app/api/auth-guard.ts, src/app/api/token.interceptor.ts, src/app/api/token.service.ts, src/app/app.routes.ts, src/app/layout/header.component.ts, src/app/login/login.component.ts, src/app/shared/error-handler/server-error.interceptor.ts
When an unauthenticated user accesses the WholeTale Dashboard, they are bounced to the login page. After login, they are dropped at the home page. This breaks the user's flow by requiring them to manually navigate back to their desired view.
Fixes #34 
Save `returnRoute` as a query string parameter when bouncing a user to the login page, and use this query param to restore their navigation target after login.
Prerequisites: Logout
2. Attempt to navigate to `/mine` without logging in
* You should be bounced to the login page
* You should see `?rd=mine` in the query string parameter
3. Login with the correct credentials
* You should be brought to the My Tales (`/mine`) view
=> Handle return route after login

src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.ts, src/app/api/models/tale.ts
After creating a Tale, editing/saving metadata does not work properly because some of the fields of the new Tale are invalid by default.
Fixes #32 
Default all required fields to reasonable defaults.
3. Create a new Tale
* You should be redirected to the Run > Metadata view for the Tale
4. Scroll down and click the "Edit" button at the bottom
* An editable form should appear
5. Scroll down and click the "Save" button at the bottom
* You should receive a toast / popup saying your Tale was saved successfully
=> Set required Tale fields to non-null default values

src/app/+run-tale/run-tale/run-tale.component.ts, src/app/framework/core/models/window.ts, src/app/framework/core/window.service.ts
When a user chooses "Export Tale" from the UI, nothing happens. This is because the `tale/:id/export` does not follow the same patterns as the other endpoints, and requires special handling.
Fixes #49 
Handle this endpoint by navigating to it directly in the browser. This requires placing our token in the URL as a query parameter.
3. From the Tale Catalog view, hover over a Tale and click "View"
* You should be brought to the Run view
4. At the top-right, expand the dropdown and choose "Export Tale"
* You may see a new tab open and then immediately close
* You should see that a download has started for a ZIP file named after the Tale ID
=> Export Tale should download a zipfile

src/app/tales/components/tale-run-button/tale-run-button.component.ts
When launching a Tale, the user is not brought to the Interact tab as expected.
Fixes #45 
Navigate to the Run > Interact view when launching a Tale.
3. Navigate to the Tale Catalog
4. Choose a Tale and click "Run Tale"
* You should be navigated to the Run > Interact view
5. Stop the Tale and navigate to the Run > Metadata view
6. Click "Run Tale" again
* You should be navigated to the Run > Interact view
=> Navigate to Run > Interact view on launch

src/app/+run-tale/run-tale/run-tale.component.html, src/app/+tale-catalog/tale-catalog/components/my-tales/my-tales.component.html, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.html, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts, src/app/notification-stream/notification-stream.component.html, src/app/shared/common/common.module.ts, src/app/shared/common/pipes/truncate.pipe.ts
Tale title is not currently truncated, which can cause UI elements to be too long and extend off the screen.
Fixes #14 
Added a reusable `TruncatePipe`
Prerequisites: at least one Tale created with a long name (100+characters)
3. Navigate to the Tale Catalog
* You should see that the Tale's long name has been truncated
4. Click "View" on the Tale
* You should be navigated to the Run > Metadata view
* You should see that the Tale title at the top is now truncated
5. Stop (if necessary), and then Run the Tale
* You should see the notification panel automatically display with a new notification
* You should see that the new notification also contains a truncated Tale title
=> Truncate Tale title throughout

src/app/+run-tale/run-tale/run-tale.component.html, src/app/+run-tale/run-tale/run-tale.component.scss, src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+run-tale/run-tale/tale-interact/tale-interact.component.html, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts, src/app/tales/components/tale-run-button/tale-run-button.component.ts
Tale "popout" icon is missing from Run view. Previous dashboard had a button allowing the user to "popout" the iframe into a new tab.
Fixes #46 
Fixes #44 
NOTE: The "Stop Tale" button properly shows that the Tale is stopping, but the Run > Interact view does not appear to update correctly
* Added the popout button to the tab bar of the Run view
* Improved the status/progress indicators on the Run > Interact view
Prerequisites: at least one Tale created and (ideally) running
3. Choose a running Tale and click "View"
* You should be brought to the Run > Metadata view
4. Click the "Interact" tab and then click "Run Tale" at the top-right
* You should see the Tale begin to start
5. Wait for the Tale to …
=> Tale popout button

src/app/+tale-catalog/tale-catalog/components/my-tales/my-tales.component.html, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.html, src/assets/sass/wholetale-dashboard.scss
Category does not display at all when browsing the Tale Catalog.
Additionally, a noticeable small white box appears over the top of the Tale title, in the case that it is too long and needs to be truncated.
* Fix `tale.categories` to `tale.category` on the Catalog view(s)
* Remove the arbitrary `height` applied to `t-title` to fix the truncation fade/gradient
Prerequisites: at least one Tale created with a very long title (e.g. `Fire influences on forest recovery and associated climate feedbacks in Siberian Larch Forests, Russia`)
3. Navigate to the Tale Catalog
* You should see the `tale.category` now appears in a yellowish font above each Tale's title
* NOTE: For LIGO Tale, this should read …
=> Fix category and title display in Tale Catalog view

src/app/tales/components/tale-run-button/tale-run-button.component.ts
When launching a third Tale, there should be a message displayed informing the user that they have reached the limit for running Tale instances. This modal does not display, and the error is simply sent to the developer console.
Fixes #52 
Use the generic `ErrorModalComponent` to display the error modal as intended.
Prerequisites: 2 Tales already running
3. Navigate to the Tale Catalog view
4. Launch 2 Tales, if you haven't already
5. Choose a Tale that is not running and click "Run Tale"
* You should see an error-modal appear, displaying the error message encountered: `You have reached a limit for running instances (2). Please shutdown one of the running instances before continuing.`
6. Click …
=> fix: handle 'too many instances' error

src/app/+run-tale/run-tale/run-tale.component.html, src/app/+run-tale/run-tale/run-tale.component.scss, src/app/tales/components/modals/copy-on-launch-modal/copy-on-launch-modal.component.html, src/app/tales/components/tale-run-button/tale-run-button.component.ts, src/assets/sass/style.scss, src/assets/sass/theme.scss
1. On creating a Tale copy, user is not brought to the new Tale's Run view
2. Fixes #27 - `copy-on-launch-modal` appears to indicate that it will *run* the Tale, when it does not
3. Fixes #26  - There is no indication that a particular Tale was copied from another Tale.
Per the [mockups](https://whole-tale.github.io/wholetale-css-mockup/src/run.html):
1. Navigate the user to the new Tale when creating a copy, as we currently do for Create or Launch
2. Adjusted the text on the `copy-on-launch-modal` to better indicate that this operation will not actually Run the Tale
3. Added a `COPY` tag to the header of the Run view, also added the missing `PUBLIC` / `PRIVATE` indicators as well
Prerequisites: LIGO Tale
2. Login to the WholeTale …
=> Run view should show COPY/PUBLIC/PRIVATE tags

src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.html, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.ts
Download links under `Involatile Data` are invalid, and contain `null`
Fixes #23 
Fix the broken links to use the same API call as the legacy dashboard.
NOTE: Girder's `item/:id/download` link returns a 303 redirect to the file's original location. This can break for particular types of files that the browser can display, which do not appear to be downloaded by default. For example, the `BBH_events_v3.json` from the `LIGO Tutorial` Tale. I believe that sending the `contentDisposition=attached` parameter is supposed to tell Girder to download the item instead of redirecting to it, but I don't think that this parameter is currently being respected in all cases.
Prerequisites: LIGO Tutorial Tale
3. …
=> Fix involatile download links on Run > Metadata view

Dockerfile.build, yarn.lock
Automated Docker builds have been broken for awhile due to dependency incompatibilities. This was likely caused by a dependabot update and went completely unnoticed.
Upgrade to NodeJS 10, sync Yarn dependencies
=> Fix Docker builds

src/app/+run-tale/run-tale/modals/register-data-dialog/register-data-dialog.component.html, src/app/+run-tale/run-tale/modals/register-data-dialog/register-data-dialog.component.ts
Fixes #93 
This PR removes the text box that allowed users to enter a folder name.
1. Open the register data modal (I went to Tale->Files->Add External Data)
2. Enter a doi or URL (eg doi:10.18739/A2M61BQ8M)
3. Search for the data
4. Select the result
5. Note that there isn't a field for the folder name
=> fix: remove the folder from the user's view and component

src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.html, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.scss, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.ts
Metadata view is missing some necessary information and styling does not very closely match the mockups.
Fixes #47 
Fixes #17 (but may still need very minor spacing fixes on read-only metadata view)
Replace edit/save/cancel with static views that more closely match the mockups provided [here](https://whole-tale.github.io/wholetale-css-mockup/src/run-meta.html).
Prerequisites: at least one Tale created (Owned Tale, does not need to be running), at least one dataset registered
3. Navigate to the Tale Catalog
4. Locate a Tale that you own and click View
5. Click the Files tab to go to the Run > Files view, then attach one or more External Datasets to the Tale
6. Click the Metadata tab to go to the Run …
=> Fix: add/style missing info on metadata

src/app/layout/header.component.html, src/app/layout/header.component.scss, src/app/layout/notification-stream/notification-stream.component.scss
The "Data Catalog" and "Compute Environment" links just contain static placeholder data.
Hide these links for now until these views are functional and add more value to the platform.
Fixes #97 - Hide the links until these views are finished
Other minor fixes on this branch:
* Fixes #84 - Adjusted notification stream margins so it no longer overlaps with the navbar
* Added missing User Guide link to the navbar (clicking icon previously did nothing)
* Display avatar in the navbar when available, disabled menu item for avatar/username, as clicking it currently does nothing
Prerequisites: none
* You should see only "Tale Dashboard" in the navbar
* You should **not** see "Data Catalog" or "Compute …
=> fix: various small navbar fixes

src/app/+run-tale/run-tale.module.ts, src/app/+run-tale/run-tale/tale-files/tale-files.component.ts, src/app/files/file-explorer/file-explorer.component.html, src/app/files/file-explorer/file-explorer.component.ts, src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.html, src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.scss, src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.spec.ts, src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.ts, src/app/files/files.module.ts, src/app/tales/pipes/tale-name.pipe.ts, src/app/tales/tales.module.ts
The MoveTo dialog was never implemented. There is already some code written that can work as a callback that this modal should execute after submission.
Fixes #40 
Fixes #92 
Fixes #91
* Implement the MoveToDialog, allowing user to change the parent folder of a given file or folder
* NOTE: This approach currently encounters issues when moving from a Tale Workspace to Home, and likely vice versa. I may be missing some bits about setting `baseParentId` properly when shifting between data sources. Unless it's an easy fix, this will likely be addressed in a follow-up ticket.
Prerequisites: at least one Tale created, at least two folders created
4. Navigate to Run …
=> feat: add move-to-dialog for changing parent folder

src/app/+run-tale/run-tale/run-tale.component.html
Clicking "Return to Dashboard" from the Run view does not always bring you back to the correct view. Currently, it is hard-coded to bring you back to `/`, which redirects to `/public` and shows the Public Tale Catalog.
This should bring you back to "My Tales" if that is where you were when you clicked it.
Fixes #36
Use the user's accessLevel for this Tale to guess where they came from. If they own the Tale, send them back to "My Tales". Otherwise, send them back to "Public Tales".
NOTE: Due to the tab-navigation behavior described in #36, this is probably the best that we can do for now.
NOTE: There is still an unhandled edge case here unless we plan to display Tales that have been created by others and shared with you under "My Tales". May need to revisit this pattern as the Tale sharing …
=> fix: adjust Return to Dashboard link based on access

src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts
When deleting a Tale from the catalog, it would remain in view.
Fixes #39 
Easy fix, but very annoying to track down what was causing it. This is probably a pattern problem with how I have implemented the catalog views.
This is probably bad practice long-term, but the two edge cases that collide here are:
1. It is unclear how often Tales are actually deleted (typically, users are bad at cleaning up zero-cost resources)
2. It is unclear how often the average user refreshes their current browser tab, and not doing so may have consequences sif  RxJS streams are not handled properly ... I may need to read up more about cleanup here
3. Create a Tale, if you …
=> fix: explicitly update tales$ binding when deleting

src/app/+run-tale/run-tale/modals/select-data-dialog/select-data-dialog.component.html, src/app/+run-tale/run-tale/modals/select-data-dialog/select-data-dialog.component.scss
Some HTTPS dataset subfolders appear to render with an excessive amount of space. 
Fixes #90 
While I still don't know what was causing this problem, adding a `width` to the first column prevents it from taking up too much space in these cases.
Appears to be related to https://github.com/whole-tale/girder_wholetale/issues/304, but I have no idea how or why. This behavior seems to only manifest with these types of HTTPS resources.
Prerequisites: at least one Tale created that you own, at least one HTTPS dataset resource registered
Example: Register https://raw.githubusercontent.com/whole-tale/dashboard/master/.travis.yml
Ideally: many different datasets registered
3. Navigate to the Tale Catalog and …
=> fix: add a width to first column to prevent whitespace on select-data-dialog

src/app/tales/models/tale.ts
See https://github.com/whole-tale/gwvolman/pull/123 for primary change and test case.
The workspaceModified field is no longer needed/used with the move to virtual resources. This field appears to be unused by the UI but present in the tale model definition.
=> Remove unused workspaceModified field

src/app/layout/header.component.html
User Guide does not open in a new tab. This disrupts user workflow if they click the button, regardless of whether the click was intentional or accidental.
Open User Guide in a new tab.
3. Click ( i ) at the top-right of the navbar
* User Guide should open in a new tab
=> fix: open User Guide in a new tab

src/app/+run-tale/run-tale/tale-sharing/tale-sharing.component.ts
I accidentally broke the Sharing tab while fixing build warnings.
Fixes #120 
Revert this change, since it was apparently not necessary anyways.
Prerequisites: at least one Tale created that you own
4. Navigate to Run Tale > Share for a Tale that you own
* You should no longer see an error pop up about `addEventListener` failing
=> fix: fix tale-sharing tab

src/app/+run-tale/run-tale/run-tale.component.ts
The EmberJS dashboard used to redirect the user to the browse view when an invalid Tale ID was encountered. AngularJS dashboard needs this behavior as well.
Fixes #108 
Redirect to "public" catalog if an error is encountered fetching the Tale in the Run Tale view.
3. Navigate directly to `/run/thisisnotarealid` in your browser
* You should be redirected to the Public Tales catalog
=> fix: redirect from run-tale to catalog on error

src/app/+tale-catalog/tale-catalog.routes.ts, src/app/+tale-catalog/tale-catalog/components/my-tales/my-tales.component.html, src/app/+tale-catalog/tale-catalog/tale-catalog.component.html, src/app/layout/header.component.html
"My Tales" should be the go-to place for users. (@craig-willis I'm well aware I said something totally opposite the other day. What can I say? I changed my mind :P)
Make `/mine` a default path. Add more descriptive message in case user doesn't have any tales.
3. You should land on `/mine` tab. `Tale Dashboard` in the header should be highlighted.
4. If you don't have any Tales you should be greeted with a new longer message containing the link to `/public` (check that it works)
5. Everything in the header (i.e. wholetale logo and 'Tale dashboard') should direct you to /mine tab.
=> fix: make mine tab the default view

src/app/layout/notification-stream/modals/view-logs-dialog/view-logs-dialog.component.html, src/app/layout/notification-stream/modals/view-logs-dialog/view-logs-dialog.component.scss, src/app/layout/notification-stream/modals/view-logs-dialog/view-logs-dialog.component.ts
View Logs modal auto refreshes, but doesn't offer a way to follow the tail of the logs.
Add a "Scroll to Bottom" checkbox to the View Logs modal, that is checked by default
Prerequisites: at least one Tale created, not running
3. Launch a Tale
* You should see the `notification-stream` appear at the top-right, offering the "View Logs" button
4. Click on "View Logs"
* You should see the `view-logs-modal` appear
* You should see a checkbox that reads "Scroll to Bottom" at the bottom-left
* You should see that "Scroll to Bottom" is checked by default
5. Scroll up as the build output continues
* You should be brought back to the bottom of the modal every 1-2 seconds
6. Uncheck "Scroll to Bottom" and …
=> feat: add an autoscroll function to views-logs-modal

src/app/+run-tale/run-tale/tale-interact/tale-interact.component.html, src/app/+run-tale/run-tale/tale-interact/tale-interact.component.scss
`tale-interact` tab may not properly handle cases when `iframe=False`
Fixes #116 
Re-test this case and make sure styling is correct
Prerequisites: at least on image with `iframe=False`:
* You can use `GET/PUT /image/:id` on Swagger UI to toggle this easily
3. Create a new Tale from the image with `iframe=False`
4. Click Run Tale to navigate to Tale Interact
* You should see a message indicating that this Tale cannot run in a n iframe and that it needs to run in a new window
* You should be offered a button to open the Tale in a new window
=> fix: ensure that tale-interact handles iframe=False

src/app/+run-tale/run-tale/modals/create-rename-version-dialog/create-rename-version-dialog.component.html, src/app/+run-tale/run-tale/modals/create-rename-version-dialog/create-rename-version-dialog.component.ts, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.ts, src/app/api/services/version.service.ts
Race condition when validating name allows user to submit invalid data. They get an error popup, but we should prevent this behavior.
Fixes #117 
Based on https://github.com/whole-tale/wt_versioning/pull/18
* For "Create" case: support `allowRename` during CreateVersion - this will guarantee unique version names by appending `(1)` or similar to resolve conflicts
* For "Rename" case: block submission of the form until name has been fully validated
Prerequisites: running https://github.com/whole-tale/wt_versioning/pull/18, at least one Tale created
3. Choose a Tale that you own and click "View"
4. Expand the Tale Versions Panel on the right side
1. Click on "Save New Version"
* You should see the …
=> feat: support allowRename, fix race condition

src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.html, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.ts
A small code change for adding a new row in the context menu for versions. This _should_ be the extent of the user interface changes for exporting versions.
To Do (WIP Tag) : As of this PR it's possible to test that the manifest has the correct version record, but I think it makes sense to do a more full test with a girder_wholetale PR for exporting particular versions & creating a version when one doesn't exist.
The gist of the testing is to make sure that particular versions of a Tale are exporting. To test, create a few different versions of a Tale, each with different kinds of data (workspace/remote data).
1. While running `make rebuild_dashboard`, check the output to see that there aren't any new linter warnigns.
1. Create a new Tale
2. Add data to the workspace & remote data
3. …
=> Export Versions

src/app/+run-tale/run-tale/modals/register-data-dialog/register-data-dialog.component.html, src/app/+run-tale/run-tale/run-tale.component.html, src/app/+run-tale/run-tale/run-tale.component.ts
Running through the test plan and noticed some minor issues:
This PR:
* Adds Dataverse and Zenodo links back to the register data modal.
* Removes "Recorded Run" menu item from Tale menu
* RTD should open in new tab/window from run menu
=> Various minor fixes

src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.html, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.ts, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts, src/app/api/events/event-data.ts, src/app/app.module.ts, src/app/layout/notification-stream/notification-stream.component.ts, src/app/layout/notification-stream/notification-stream.module.ts, src/app/layout/notification-stream/notification-stream.service.ts, src/app/shared/common/common.module.ts, src/app/shared/common/components/alert-modal/alert-modal.component.html, src/app/shared/common/components/alert-modal/alert-modal.component.spec.ts, src/app/shared/common/components/alert-modal/alert-modal.component.ts, src/app/shared/common/components/confirmation-modal/confirmation-modal.component.html, src/app/shared/common/components/confirmation-modal/confirmation-modal.component.spec.ts, src/app/shared/common/components/confirmation-modal/confirmation-modal.component.ts, src/app/shared/error-handler/error-handler.module.ts, src/app/tales/components/tale-run-button/tale-run-button.component.ts, src/app/tales/sync.service.ts
When multiple browser tabs are open, any edits to the Tale in one browser cause the other tabs to go out of sync. 
Integrate with https://github.com/whole-tale/girder_wholetale/pull/445 to provide updates to the UI state via Server-Side Eventing. As resources change in the backend, we will attempt to refresh the frontend data to keep the state in sync.
I am currently only handling `wt_tale_updated` event in the `run-tale` component and subviews to test out the pattern, and will start expanding to cover the other state update events that the backend is sending.
NOTE: There was a `TransferHttpCacheModule` that was caching GET requests. I have blindly disabled it for now, so we may see a (hopefully minor) performance hit. If the platform becomes unstable as a result, I can look into trying …
=> First-pass at a pattern for handling state updates from SSE

package.json
The `package.json` had information about the ng-seed/universal package. Updated to be about WT dashboard.
=> Update package information for release

src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.html
Fields names / order are inconsistent between the rendered (read-only) and editable views for Run > Metadata.
Fixes #142 
Move, reorder, and rename fields to match the order agreed upon in #142.
Prerequisites: at least one Tale created, at least one Dataset registered and attached to the Tale
3. Navigate to Run > Metadata for a Tale that you own
* You should see the following read-only fields (in order): Title, Created By, Authors, Category, Environment, License, Description, Datasets Used, Related Identifiers, Published Location, Date Created, Last Updated
4. Scroll to the bottom and click Edit
* You should be brought to the editable view for Run > Metadata
* You should see the following editable …
=> fix: reorder / rename fields for consistency on Run > Metadata

src/app/+run-tale/run-tale/modals/select-data-dialog/select-data-dialog.component.ts, src/app/+run-tale/run-tale/tale-files/tale-files.component.ts, src/app/+run-tale/run-tale/tale-sharing/tale-sharing.component.ts, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts, src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.ts, src/app/api/models/sortdir.ts, src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.html, src/app/files/file-explorer/modals/move-to-dialog/move-to-dialog.component.ts, src/app/files/models/file-element.ts
Some fetched listings on https://dashboard.stage.wholetale.org are incomplete. Girder has a non-zero default `limit` set for these HTTP requests, so we are not getting the full list sent back.
This default behavior will be helpful later, when we consider adding paging to these views, but for now it is problematic.
Fixes #150 as a temporary workaround 
Long-term, we should look into adding paging to the controls where we expect this many results to be listed
Set a `limit: 0` on each of the relevant fetches.
I basically did a grep for the word "list", and added a limit for most of the resulting calls:
```bash
$ grep -ir 'service' src/app | grep -v html | grep -v scss | grep -vi listener | grep -i list | grep -v src/app/api
src/app/+user-settings/modals/connect-apikey-modal/connect-apikey-mod …
```
=> temp fix: add "limit: 0" to most fetches to bypass Girder default

src/app/+run-tale/run-tale/tale-files/tale-files.component.ts
**Problem**:
I expect users will more often interact with the Tale Workspace than External Data.
**Approach:**
This PR sets the Tale Workspace as the default selection on the Files panel
**Test:**
* Create or open an existing tale
* Select the files tab
* Note that Tale Workspace is selected by default
=> Default selection to Tale Workspace

src/app/layout/header.component.html
"Report a Problem" button went away when the footer was removed/hidden.
* Add this functionality back in the navbar
* Add tooltips to pulled-right navbar links
* You should see the "bug" icon in the navbar
3. Hover over the "bug" icon in the navbar (and Users' Guide / Notification buttons)
* You should see a tooltip appear after a few seconds reading "Report a Problem"
4. Click the "bug" icon
* You should see https://github.com/whole-tale/whole-tale/issues open in a new tab
=> Add "report a problem" button to the navbar

src/app/layout/notification-stream/notification-stream.component.html, src/app/layout/notification-stream/notification-stream.component.scss
Fixes whole-tale/whole-tale#92
Make it green (positive) button. I can be talked out of "fluid" in favor of "floated right".
1. Deploy
2. Click on notification panel and see how it looks and feels without any message
3. Create a Tale and build image
4. See how notification panel looks and feels.
=> fix: make notification ack button stand out

src/app/+tale-catalog/tale-catalog/components/my-tales/my-tales.component.html, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.html, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts, src/app/+tale-catalog/tale-catalog/components/shared-tales/shared-tales.component.html
**Problem**:
With the new event handling implementation, deleting a tale from the catalog results in a double refresh.
**Approach**:
Remove the refresh from the `openDeleteTaleModal` and rely on the tale removed event handling instead.
**Test**:
1. Create a tale
2. Return to dashboard
3. Delete the tale and confirm that the view is only refreshed once
=> Double refresh on delete

src/app/+run-tale/run-tale/modals/publish-tale-dialog/publish-tale-dialog.component.html, src/app/+run-tale/run-tale/modals/publish-tale-dialog/publish-tale-dialog.component.ts, src/app/+run-tale/run-tale/modals/register-data-dialog/register-data-dialog.component.html, src/app/+run-tale/run-tale/modals/register-data-dialog/register-data-dialog.component.ts, src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.html, src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.ts, src/app/layout/header.component.html, src/app/layout/header.component.ts, src/app/login/login.component.html, src/app/login/login.component.ts, src/assets/env.template.js
Fixes #163 
Documentation URLs are hardcoded, pointing to stable
Add new env var `RTD_URL` that is used as a base URL in the creation of documentation links.
Deploy with https://github.com/whole-tale/deploy-dev/pull/48
2. Goto https://dashboard.local.wholetale.org/login, confirm TOS URL points to https://wholetale.readthedocs.io/en/latest/tos
3. Goto https://girder.local.wholetale.org/api/v1/integration/dataverse?datasetPid=doi%3A10.7910%2FDVN%2F3MJ7IR&siteUrl=https%3A%2F%2Fdataverse.harvard.edu, confirm "Why would I do this" points to latest
3. Check header "i", Tale > Read the docs, Publish, register data
=> Add configurable documentation URL

src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.html
In the quickstart documentation, we instruct users to copy-on-launch the LIGO tale. However, on production there are now 3 public LIGO tales -- which one should they use?
This PR adds the original/copy indicator to public tales
* Deploy this PR
* Register LIGO tale
* Copy-on-launch LIGO tale and set to public
* Goto Public Tales tab and confirm that copy/original display
=> Added original/copy indicator on public tales

src/app/+run-tale/run-tale/run-tale.component.html, src/app/+run-tale/run-tale/run-tale.component.scss, src/app/+run-tale/run-tale/tale-files/tale-files.component.scss, src/app/+run-tale/run-tale/tale-interact/tale-interact.component.scss, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.scss, src/app/files/file-explorer/file-explorer.component.scss
There is a bunch of extra padding around the `iframe` on Run Tale > Interact. This makes it difficult to use the view within the `iframe`, as there is not much space to see.
Fixes #168 ?
* Remove as much padding as possible from around the iframe without disturbing other parts of the UI.
* Add the same padding values back to Run Tale > Metadata
Note that the bottom of the panel is a special case - because of the unique scrolling behavior and how painful it is/was to tweak those margins across all views. If we are ok with the panel stretching off the bottom of the page, then we can revisit this.
Also, please ignore the broken/fake login screen here (WT hates that I use `localhost:4200` for development and throws security errors, as mentioned in the dev meeting)
Prerequisites: at least one …
=> Remove padding around iframe

src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.html, src/app/+tale-catalog/tale-catalog/components/running-tales/running-tales.component.html
View tale when tale is running should display interact page, not metadata
1. Run a Tale
2. Click on the view button.
=> fix: view for a running tale should display interact

src/app/+user-settings/modals/connect-apikey-modal/connect-apikey-modal.component.html, src/app/+user-settings/modals/connect-apikey-modal/connect-apikey-modal.component.ts
`docs_href` in connect api_key account was hardcoded, but it would be nice if it took `resource_server` into account.
Solves the problem by using a template string. Only show href if resource_server is selected.
1. Checkout this branch locally, rebuild the dashboard (needs https://github.com/whole-tale/girder_wholetale/pull/479)
3. Go to settings page
4. Select Dataone.
5. Select one of the CNs.
6. Follow "Get from DataONE"
7. Confirm you get a token.
=> fix: make 'Get token from url' for API keys dynamical

src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.html, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.ts
* DOI links in related identifiers are relative to dashboard because of missing protocol
* Datasets Used links go to Tale Workspace instead of External Data
* Prefix DOI urls with `https://`
* Datasets Used links go to External Data
* Create a tale
* Register and add a dataset, e.g.:
* ~DataONE: doi:10.18739/A2CN6XZ7H~
* DVN: doi:10.7910/DVN/SZ9YXZ
* Zenodo: doi:10.5281/zenodo.16384
* MDF: doi:10.18126/M2301J
* Go to Metadata page
* Confirm Related Identifier links work as expected
* Confirm Datasets Used links go to File > External Data
=> Fix dataset and DOI links

src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+tale-catalog/tale-catalog/components/public-tales/public-tales.component.ts, src/app/layout/notification-stream/notification-stream.component.ts, src/app/tales/components/tale-run-button/tale-run-button.component.ts, src/app/tales/sync.service.ts
UI does not currently handle `wt_instance_error` notification
Bold C&P from `wt_instance_running` implementation
* Depends on https://github.com/whole-tale/gwvolman/pull/145 and https://github.com/whole-tale/girder_wholetale/pull/480
* Modify `setup_girder.py` to set the command for JupyterLab to something that doesn't exist (e.g., `thisdoesnotexist`)
* `make clean && make dev`
* Create  JupyterLab tale and Run
* Note progression of notifications (building image, creating volume, starting container)
* Job should fail with "Error: starting container"
* View logs, note stack trace about executable not on PATH
* Run button should change to "Error!" and "Tale launching" > "Something went wrong."
=> Added handling for wt_instance_error

src/app/+run-tale/run-tale/tale-files/tale-files.component.ts
Errors thrown upon folder creation in file browser are ignored
Fixes #180 
Catch error and display it using `ErrorModalComponent`
Follow #180
=> fix: show error modal in createFolder. Fixes #180

src/app/+run-tale/run-tale/tale-files/tale-files.component.ts, src/app/files/file-explorer/file-explorer.component.html, src/app/files/file-explorer/file-explorer.component.scss, src/app/files/filesize.pipe.ts, src/app/files/models/file-element.ts
File uploads do not show their progress
Fixes #167 
* Add a basic progress bar that shows a simple percentage (no estimated time or granular byte count, nothing fancy)
3. Navigate to Run Tale > Files
4. Upload a File (larger than 200MB or so)
* You should see a progress bar and percentage now appear above the file Size as it uploads
5. Wait for the file to finish uploading
* You should see the progress bar update over time
* You should see the progress bar disappear once the file upload is complete
=> feat: add progress indicator for file uploads

src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.ts, src/app/+tale-catalog/tale-catalog/tale-catalog.component.ts
See #193 
Parse `api` query parameter and send it back as `lookupKwargs.base_url`
Explained in #193 (change `.stage` to `.local` in all urls)
=> Allow to import Tales/Binders from testing DataONE deployments

src/app/files/file-explorer/file-explorer.component.html, src/app/files/file-explorer/file-explorer.component.scss
Newer versions of Chrome appear to now be respecting settings that were previously ignored.
Fixes #200  ? somehow?
* Change the `flex-direction` on the container where the files table is listed (from `row` to `column`)
NOTE: I have no idea why this suddenly broke in a new version of Chrome, or if this fix will have other weird side-effects. Keep this in mind when testing and keep note if you see any strange behavior.
Prerequisites: at least one Tale created, at least one file/folder in Home folder
3. Navigate to Run > Files > Home for a Tale that you own
4. Upload one or more files and/or create multiple folders
* You should see that the files / folders listed here no longer stretch to take up all …
=> fix: change the flex direction on files table container

src/app/+run-tale/run-tale/tale-files/tale-files.component.ts, src/app/files/file-explorer/file-explorer.component.html, src/app/files/file-explorer/file-explorer.component.ts
Files dropdown menu stays open indefinitely unless toggled by clicking the button again
Fixes #10 
Also Fixes #8 
* #8: force re-render if `currentPath` changes
* #10: Restore expected default behavior here by initializing the dropdown "correctly" to account for the async nature of the view - dropdown should now close if user clicks anywhere outside of the dropdown menu
Note: there is still a race condition in this approach if the folders/files take longer than `1000ms` to fetch then the dropdowns may not initialize properly. I am not yet sure how to remedy this problem - too long of a timeout and the user can/will notice the delay in dropdown initialization (especially when changing navs), too short and this will cause the race condition to happen more frequently.
Prerequisites: at least …
=> fix: race condition in Run > Files, close files dropdown when clicking elsewhere

src/app/+run-tale/run-tale/run-tale.component.ts, src/app/api/models/image.ts, src/app/api/models/instance.ts, src/app/api/models/tale.ts, src/app/tales/components/tale-run-button/tale-run-button.component.html, src/app/tales/components/tale-run-button/tale-run-button.component.scss
Run View contains stale data after Tale import completes - needs manual refresh to pick up newly-registered datasets, related identifiers, etc
Fixes #137 
Fixes #121 
* Wire up the Run Tale view to the SyncService to refresh Tale data when import completes for the Tale
1. Checkout and run this branch locally, rebuild the dashboard
3. Import a Tale (preferably a large Tale that take awhile to import and/or ultimately fails)
* You should be brought to the Run view
* You should see that the "Run Tale" button is disabled and reads `Importing...`
4. Wait for the Tale import to finish
* On failure, you should see that the button stays disabled and reads `Import Failed`
* On success, you should see the "Run Tale" button now appears as expected, allowing the …
=> feat: indicate tale import status via the Run button

.gitignore, angular.json, entrypoint.sh, src/app/+tale-catalog/tale-catalog.module.ts, src/app/api/api-configuration.ts, src/app/api/token.interceptor.ts, src/app/app.module.ts, src/app/files/file-explorer/file-explorer.component.html, src/app/files/file-explorer/file-explorer.component.ts, src/app/login/login.component.ts, src/app/shared/core/log.service.ts, src/app/shared/core/window.service.ts, src/app/shared/shared.module.ts, src/assets/env.template.js, src/assets/env.template.json, src/index.html
I'm not sure how this wasn't caught during my own testing, but the Docker container seems to only bring up a blank page.
This was likely a result of the Angular 9 upgrade, as lots of things moved around there.
* Set default `LogLevel` to `Error` - previous value of `Info` was somehow hiding valuable error messages in the console
* Move `ApiModule` import from `AppModule` to `SharedModule`, fetch `env.json` from static file when initializing `WindowService` - this fixed a circular dependency
* Replace `env.js` with a static JSON file `env.json` - this seemed to behave differently when using `ng build --prod` vs `ng build`?
Setup:
Because the `entrypoint.sh` has changed, we need to build a new image:
1. `docker build -t yourdockeruser/ngx-dashboard:post-migration-fix .`
2. `docker push …
=> Fix blank page error in Docker

src/app/tales/components/tale-run-button/tale-run-button.component.ts, src/app/tales/sync.service.ts
When a Tale finishes starting up when the user is on the Interact tab, the view does not refresh automatically to show the Tale.
Instead, the view should automatically update (and not require navigation/refresh) to display the running Tale.
The `tale-run-button` lives on the Run View (as well as on the Catalog View). This component takes care of starting / stopping Tales and previously held the logic for polling for instance status.
I think the issue here was that when an update was received from the SyncService, `emit()` was not being called to output this status change to the parent component.
Now, `tale-run-button` should call `.emit()` to `@Output` the new instance status to the `run-tale` parent component as expected.
I also improved some of the logging to print out the actual status …
=> Instance running should update interact tab

src/app/+run-tale/run-tale/modals/tale-version-info-dialog/tale-version-info-dialog.component.html, src/app/+run-tale/run-tale/modals/tale-version-info-dialog/tale-version-info-dialog.component.ts, src/app/+run-tale/run-tale/run-tale.component.html, src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.html, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.ts, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.html, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.ts, src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.ts, src/app/api/models/tale.ts, src/app/api/services/tale.service.ts, src/app/tales/components/rendered-tale-metadata/rendered-tale-metadata.component.e2e-spec.ts, src/app/tales/components/rendered-tale-metadata/rendered-tale-metadata.component.html, src/app/tales/components/rendered-tale-metadata/rendered-tale-metadata.component.scss, src/app/tales/components/rendered-tale-metadata/rendered-tale-metadata.component.spec.ts, src/app/tales/components/rendered-tale-metadata/rendered-tale-metadata.component.ts, src/app/tales/tales.module.ts
Viewing a Tale "Version Info" only shows raw JSON.
Fixes #144 
Show rendered Tale metadata from the selected version instead of raw JSON.
* Add new API call to `TaleService` for `GET /tale/{id}/restore`
* Refactor `tale-metadata-tab` to isolate the readonly part into a new component called `rendered-tale-metadata`
* Replace content of TaleVersionInfoDialogComponent to display the new `rendered-tale-metadata` component
Prerequisites: at least on Tale created that you own
1. Checkout this branch locally (along with https://github.com/whole-tale/wt_versioning/pull/24), rebuild the dashboard
3. Navigate to the Run View for a Tale that you own
4. Create a version of the Tale (if you haven't already)
5. Expand the dropdown beside the new version and choose …
=> Render Tale Metadata when displaying "Version Info" instead of raw JSON

src/app/+run-tale/run-tale/tale-files/tale-files.component.ts, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.ts, src/app/+run-tale/run-tale/tale-sharing/tale-sharing.component.html, src/app/+run-tale/run-tale/tale-sharing/tale-sharing.component.ts, src/app/files/file-explorer/file-explorer.component.html, src/app/files/file-explorer/file-explorer.component.ts, src/app/layout/notification-stream/notification-stream.component.ts, src/app/shared/core/window.service.ts, yarn.lock
Various small bugs that have been filed recently
Fixes #241 
Fixes #240 
Fixes #237 
Fixes #236 
Fixes #235 
* Updated `caniuse` for more accurate browser compatibility hints (this was recommended by our CLI build tools)
* #241: Fixed missing icon for RunStatus.RUNNING - `fa-refresh` no longer appear to work as they did in previous versions of FontAwesome, so `fa-sync` or `fa-sync-alt` should be used instead
* #240: Fixed Export dropdown option for Tale Version on Tale History Panel - `windowService.open` was no longer working as expected
* #237: Fixed `apiUrl` being ignored - the `apiUrl` from `env.json` should once again reflect in the API calls (see note below)
* #236: Fixed "Add" button always being disabled on Run > Share - I suspect that an upgrade might have broken this.. entire …
=> Various bugfixes: dropdown behavior, export version, missing icon, add user, apiUrl config, update caniuse

src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.html, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.ts, src/app/tales/pipes/tale-version-name.pipe.ts
Fixes #234 
* Order by `created` date, instead of `updated` date
* ??? - fix for the rename issue may need backend signal work, or else the `SyncService` is missing some implementation
* Link to Run > Files > Tale Versions and/or Run > Files > Recorded Runs directly from the Tale History Panel
Prerequisites: at least on Tale created, at least one Tale Version created, at least one Run created from the Version
3. Navigate to Run Tale and create a Version and a Run (if you haven't already
4. Expand the Tale History Panel and view the timeline
* You should see timeline is now sorted by `created` date
* You should see that the version/run name is now a link
5. Rename the version
* You should see the …
=> Tale Version Panel fixes: orderby created date, link directly to runs/versions

src/app/+run-tale/run-tale/tale-files/tale-files.component.ts, src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.ts, src/app/api/models/run.ts, src/app/api/models/version.ts, src/app/files/file-explorer/file-explorer.component.ts, src/app/files/models/file-element.ts
Fixes #249 - If renaming a file or folder, the UI shows the new name as if it were successful
Fixes #250 - If a user is not logged in and attempts to trigger AiWT, their URL parameters are double-encoded and are not properly decoded
* #249: store `prevName` when renaming, roll-back to this name if the rename fails
* #250: decode all params for AiWT (in case they are double-encoded by the login redirect)
2. Navigate to Run > Files (Home or Workspace) for a Tale that you own
3. Create a folder named `folder1`
4. Create a second folder named `folder`
5. Attempt to rename `folder2` to `folder1`
* You should see that an error modal appears on the screen indicating that the rename has failed
* You …
=> Fix AiWT URL encoding / roll-back when rename fails

src/app/+run-tale/run-tale/run-tale.component.html
See https://github.com/whole-tale/ngx-dashboard/issues/260 for test case
This PR simply disables the Export menu as we already do publish. Another option would be to prompt the user to copy the tale.
=> Disable export menu option if not writable

src/app/+run-tale/run-tale/run-tale.component.html, src/app/layout/header.component.html
Per evaluator feedback (https://github.com/whole-tale/whole-tale/issues/112):  "It would be nice if when you hovered over a symbol (like the box with the arrow coming out of it in the upper right) it would give you a little text saying what it did, rather than just having to click the button and see what happens. " (4)
I went ahead and added tooltips for more than just the pop-out.
* Added tooltips
* Hover over the header icons (docs, bug, notifications, user menu) and the tale pop-out and history icons. Tooltips should display.
=> Add tooltips to textless buttons

src/app/+run-tale/run-tale/tale-files/tale-files.component.ts
After performing a rename or upload, the file's context dropdown menu breaks.
Fixes #259
The last fix to this logic changed things so that it only looks at the length of the list to perform these updates. An upload completing itself and a rename are two cases where the length of the list stays the same.
Added some additional post-upload and post-rename logic to force this context menu to work after the upload/rename is complete - NOTE: when this fires, it will cause all dropdowns similar to the behavior we saw before. If the user is uploading many small files, they may run into behavior like before, where the menu is not open long enough to interact with it.
3. Navigate to Run > Files > Home
4. …
=> fix: rename/upload shouldnt break the file context menu

src/app/app.component.ts, src/app/login/login.component.html, src/app/login/login.component.scss, src/app/login/login.component.ts, src/index.html
Our current login page makes it practically impossible to navigate (and login) using screen readers, more over our main oauth provider (Globus) makes it impossible to select university specific auth provider.
1. Add a structure to the login page ("heading", "banner", "main content", "contentInfo")
2. Allow to skip unimportant parts of the page ("heading", "banner") via a dedicated skip link, that's only visible on focus and clearly labeled with text.
3. Convert a single non-descriptive "Access + image" button into a) header "Sign in to Whole Tale" and a simple "Sing in with <provider>" button.
4. Add a GitHub as an additional OAuth provider
5. Make a login button selectable via keyboard and act on "enter" being pressed to follow the link. 
See comparison:
Prerequisites: Set up GitHub …
=> Add accessibility features to the login page

package.json, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.html, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.ts, tsconfig.json, yarn.lock
I won't lie: testing step 11. from https://github.com/whole-tale/ngx-dashboard/pull/274 made me sad. Not that anything is wrong with it, but I was really sad to learn that backend allows that. We're gonna fix it soon, but that's beside the point. We shouldn't allow user to put junk into their tales and I think that validating it before sending it to the server is the simplest approach.
1. Fetch JSON schema from the backend whenever metadata editor is opened.
2. Using [ajv](https://ajv.js.org/) create a validator function using a proper schema.
3. Whenever advanced config string changes validate it and return error message.
1. Modify `wholetale` plugin locally by adding `"additionalProperties": False,` to `containerConfigSchema` in `server/schema/misc.py`.
2. Follow steps from …
=> Add json schema validation for Tale Advanced Config section

package.json, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.html, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.ts, tsconfig.json, yarn.lock
There are several advanced features that cannot currently be edited / configured via the Metadata view in the UI
Fixes #271 
Add an "Advanced" section the the Run Tale > Metadata view that allows the user to adjust the Tale configuration (`tale.config`). This includes very basic JSON validation that is not aware of required fields or the expected types within
See https://recordit.co/gFWiCmPSQD for demonstration
4. Navigate to Run Tale > Metadata for a Tale the you own
* You should see the read-only / rendered Metadata view
5. Click the Edit button at the bottom
* You should see the editable Metadata view
6. Scroll all …
=> Run Tale > Metadata > Advanced > Tale Config section

src/app/+tale-catalog/tale-catalog/pipes/search-tales.pipe.ts
Searching for tales is currently case sensitive and doesn't include the category field. This fixes that.
Update the `SearchTalesPipe` to match existing fields irrespective of case and add category as a searched field.
2. Create two tales: 1) Title: ABC 123 Category: XYZ and 2) Title: abc 123 Category: efg
3. Search for "abc" both tales should result; search for "xyz" and the first tale should appear
I was surprised to learn that we implemented a Javascript-based search instead of using the  GET `tales` endpoint's text search feature. But this should work for now.
=> Make "search" case insensitive and include category field

src/app/+run-tale/run-tale/run-tale.component.html, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.html, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.ts
I was tinkering and maybe these fix some of the issues I reported in https://github.com/whole-tale/ngx-dashboard/pull/277:
* Add a tooltip to the run button to indicate that the user needs to sign in?
* With https://github.com/whole-tale/wt_versioning/pull/45, allow non-logged-in user to view versions/runs but not see export or restore menu.
=> Public access to catalog (suggestions)

angular.json, package.json, src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+run-tale/run-tale/tale-interact/tale-interact.component.ts, src/app/api/token.interceptor.ts, src/app/layout/header.component.ts, src/app/layout/notification-stream/notification-stream.component.ts, src/app/layout/notification-stream/notification-stream.service.ts, src/app/shared/error-handler/server-error.interceptor.ts, src/app/tales/components/tale-run-button/tale-run-button.component.ts
Some remaining problems still linger after merging #277 and #282. Namely
Fixes #283 - `notification-stream` sometimes does not display when launching a Tale, events are not handled properly
Fixes #284 - silent 401 error in the console when attempting to access a private Tale before logging in
Fixes #285 - user can still view stale data after logging out when viewing a private Tale
* #283 - Reconnect to `notification-stream` when user is logged in, disconnect on logout
* #284 - Re-route to login automatically if user attempts to access a private Tale
* #285 - Logout while on private Tale's Run view now redirects to `/public` after logout
Prerequisites: logged out, at least one Tale (private; not public, not shared)
2. Navigate directly …
=> fix: notifications should appear without refresh, fix login/logout edge cases for private Tale

src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.html, src/app/+tale-catalog/tale-catalog/modals/create-tale-modal/create-tale-modal.component.ts, src/app/+tale-catalog/tale-catalog/tale-catalog.component.html, src/app/+tale-catalog/tale-catalog/tale-catalog.component.ts
* Creating or importing a tale based on a DOI or dataset URL currently relies on AinWT integration, knowledge of how to construct an AinWT URL, or use of an external tool (e.g., [rtd/ainwt](https://wholetale.readthedocs.io/en/latest/ainwt.html), [bookmarklet](https://wholetale.readthedocs.io/en/latest/users_guide/integration.html#bookmarklet-for-analyze-in-whole-tale)). 
* Using the `/mine?uri=` approach during AinWT is not dataset-aware (i.e., does not perform lookup) and also not Tale-aware (which is important because tales cannot be mounted read-only and must be imported).
* Add "Create New Tale from DOI" to the "Create New Tale" menu and flow. This includes calling `lookup` to populate title and determine whether dataset is a tale.
* Handle both create and AinWT cases
1. Checkout this …
=> Create Tale from DOI

src/app/+run-tale/run-tale/tale-sharing/tale-sharing.component.html, src/app/+run-tale/run-tale/tale-sharing/tale-sharing.component.ts
On the Run > Share view, if the user clicks Add multiple times in succession then they can end up with duplicate entires in the access list.
Fixes #266 
Disable the "Add" button until we are finished processing the current request.
Prerequisites: at least one Tale that you own
3. Navigate to Run > Share for a Tale that you own
4. Search for a user (e.g. `John Doe`)
5. Quickly attempt to press Add multiple times
* You should be unable to click Add multiple times, as it should disable while processing the current request
=> fix: prevent user from clicking Add multiple times in Run > Share

src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+run-tale/run-tale/tale-files/tale-files.component.html, src/app/+run-tale/run-tale/tale-files/tale-files.component.ts, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.html, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.ts, src/app/api/services/tale.service.ts, src/app/files/file-explorer/file-explorer.component.html, src/app/files/file-explorer/file-explorer.component.ts
~~`copyTale` should copy the specific version that the user is viewing~~
The UI should offer a way to clone a specific Tale version as a new Tale, without including all other/previous version info.
Fixes #267
* ~~Send `versionId` along with the API request to `/tale/:id/copy`~~
* Add a new dropdown item for Tale Versions: "As New Tale"
Prerequisites: at least one Tale created, at least two versions created
1. Checkout and run this branch locally, rebuild the dashboard
2. Log into the WholeTale Dashboard
3. Create a Tale (if you haven't already)
4. On the Tale, create two distinct versions (if you haven't already)
5. Navigate to Run > Files > Tale Versions for the Tale
* You should see your 2 versions listed here
6. Expand the dropdown beside one of the Versions and choose "As New Tale"
* …
=> feat: copyTale should copy specific Tale version

src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+run-tale/run-tale/tale-files/tale-files.component.ts
Some issues with the file browser:
* #299: When user creates a folder it does not immediately appear in the file browser
* #297: When user renames a folder it breaks the dropdown menu of that folder
Fixes #299
Fixes #297
* Call `this.load()` after folder creation, rather than manually adding the new folder to the list - this will force a full refresh of the contents of the file browser
* Call `this.initDropdowns()` in every possible callback of `load()` - we should rely on calling `this.load()` anytime the user makes a change to directory structure (e.g. copy, move, rename, upload, create, etc) and this should correctly re-init all of the dropdowns on the file browser if any DOM elements need to be re-rendered (which somehow breaks their dropdown menu)
Prerequisites: at least one Tale to …
=> fix: create folder without refresh, fix dropdowns after rename folder

src/app/+run-tale/run-tale/run-tale.component.ts, src/app/+run-tale/run-tale/tale-interact/tale-interact.component.html, src/app/+run-tale/run-tale/tale-interact/tale-interact.component.ts
An unauthenticated user can end up on the Interact tab, which does not work properly if the user is not logged in.
Fixes #296
* Force users to login if they reach the Interact tab without doing so (note that Interact tab is hidden from UI if user is not logged in)
* Add a message to the Interact page that the user must Sign In to Interact - just in case the automatic redirect fails
Prerequisites: at least one public Tale
4. Mark the Tale as public
5. Navigate to the Interact tab and copy the URL
6. Sign out and open a new incognito window
7. Paste the Interact URL that you saved previously
* You should be prompted to log in
8. Enter your credentials (2FA, …
=> fix: interact tab should route user through login if needed

src/app/+run-tale/run-tale/run-tale.component.html, src/app/+run-tale/run-tale/run-tale.component.scss, src/app/+run-tale/run-tale/tale-files/tale-files.component.html, src/app/+run-tale/run-tale/tale-files/tale-files.component.scss, src/app/+run-tale/run-tale/tale-files/tale-files.component.ts, src/app/+run-tale/run-tale/tale-interact/tale-interact.component.scss, src/app/+run-tale/run-tale/tale-metadata/tale-metadata.component.scss, src/app/+run-tale/run-tale/tale-sharing/tale-sharing.component.scss, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.html, src/app/+run-tale/run-tale/tale-versions-panel/tale-versions-panel.component.scss, src/app/files/file-explorer/file-explorer.component.html, src/app/files/file-explorer/file-explorer.component.scss, src/app/files/file-explorer/file-explorer.component.ts
Tale Versions Panel has some odd styling concerns - default size is a bit too small, scroll bars always show even when not needed
Fixes #290 
Clean up the styling here to improve the look&feel of the Tale Versions Panel
Default state (no versions created):
With one or more versions created (do not show scroll bars):
With many versions created (show scroll bars):
Prerequisites: at least one Tale created that your have access to
3. Navigate to Run Tale and expand the Tale Versions Panel on the right
* You should see the Version timeline now has slightly better styling
4. Add a few more versions
* You should see that scroll bars only appear if timeline content becomes too long to fit on the screen
=> fix: tale version panel height, file-browser loading indicator, css prettification on all of run-tale view

src/app/layout/notification-stream/notification-stream.component.html, src/app/layout/notification-stream/notification-stream.component.ts
There is no way to cancel running jobs from the WholeTale Dashboard
Fixes #307 
* NotificationStream - add a Cancel button beside the progress bar of running jobs
* Show this button only if the `event.data.state === 'active'`
* Button should only be clickable if `event.data.resource.jobs.length` is truthy
3. Launch a Tale
* You should be brought to the Run Tale page
* You should see the NotificationStream appear at the top-left with a new event
* You should see that the new event shows that your Tale image is now building
* You should see a red X button beside this running job - this is the Cancel button
4. Click the X beside the running Job
* NOTE: you may …
=> feat: notification stream - add a Cancel button beside job progress bar

src/app/api/services/wholetale.service.ts, src/app/layout/header.component.html, src/app/layout/header.component.scss, src/app/layout/header.component.ts
Branding items such as the dashboard instance name, header color, and logo are hardcoded. With https://github.com/whole-tale/girder_wholetale/pull/572, this PR adds branding configuration support via a new `/wholetale/settings` endpoint.
- See https://github.com/whole-tale/girder_wholetale/pull/572 for test case
=> Enable basic branding

src/app/layout/header.component.html, src/app/layout/header.component.ts
Data catalog link is hardcoded
Use `rootUrl` to derive a proper link
>  **Note**
> Other seemingly unrelated changes were made to make linter happy...
Prerequisites: 
2. Enable Data Catalog
3. Go to dashboard and check Data Catalog links to girder.
=> fix: don't hardcode data catalog url
